#! /bin/sh

set -e

case "$1" in
    configure)
    if [ -x /usr/sbin/update-initramfs ]; then
        echo
        update-initramfs -u
    fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installsystemd/12.10ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'ykfde-suspend.service'; then
		# This will only remove masks created by d-s-h on package removal.
		deb-systemd-helper unmask 'ykfde-suspend.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'ykfde-suspend.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'ykfde-suspend.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'ykfde-suspend.service' >/dev/null || true
fi
# End automatically added section

