#!/usr/bin/ash

cryptname="${1}"

# Start udev from initramfs
/usr/lib/systemd/systemd-udevd --daemon --resolve-names=never

# Synchronize filesystems before luksSuspend
sync

# Suspend root device
[ -z "${cryptname}" ] || cryptsetup luksSuspend "${cryptname}"

# Suspend the system
echo mem > /sys/power/state

# Resume root device
RESUME=1

. /init_functions
parse_cmdline < /proc/cmdline
. /hooks/ykfde; run_hook

# Stop udev from initramfs, as the real daemon from rootfs will be restarted
udevadm control --exit
